name: Deploy gebetszeiten.ics to GitHub Pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 2 * * *"  # täglich um 02:00 UTC (04:00 Berlin-Zeit)
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests ics pytz

      - name: Run gebetskalender.py
        run: python gebetskalender.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
